version: '3.7'

services:
  app:
    image: 'regyl/oil-spills-monitoring:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oil-spill
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=SomeUselessPassword02
    ports:
      - '85:85'

  db:
    image: 'postgres:13'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SomeUselessPassword02
      - POSTGRES_DB=oil-spill